#include <iostream>
#include <cstdio>
#include <cstdlib>

using namespace std;

int main()
{
	/*
	   tmpfile() creates and opens a temporary file in binary read/write(wb+) mode
	   with a unique autogenerated filename.
	   
	   The file will be auto deleted when it is closed by the program(by executing fclose())
	   or when the program terminates.
	   
	   If successful it returns a stream pointer to the temporary file created and null
	   on failure.
	   
	   It takes no parameters.
	
	*/
	    FILE *fp;
	    
	    fp = tmpfile();
	    
	    char writeToFile[50]  = "Creating a temporary file";
	    
	    if(fp==NULL){
			perror("Error creating temporary file");
			exit(1);
		}
		fputs(writeToFile,fp);
		rewind(fp);
		
		char readFromFile[50];
		fgets(readFromFile,sizeof(readFromFile),fp);
		cout<<readFromFile;
		fclose(fp);
		

	return 0;
}